baseurl = "https://www.sjaconsulting.com/"
languageCode = "en-us"
title = "SJA Consulting"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
 	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "Suzanne Aldrich"
	description = "Owner, SJA Consulting"

	# Navigation
	[params.navigation]
		brand = "SJA Consulting"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "SJA Consulting"
		subtitle   = "Website Development & IT Solutions"
		buttonText = "Our Philosophy"

	# About section
	[params.about]
		headline    = "Designing a usable web."
		description = "Designing a usable web requires a commitment to high standards of form and function. Specializing in developing aesthetic solutions utilizing open-source technologies, we've succeeded in delivering cost-effective systems that are secure and easy to use."
		buttonText  = "Get Started"

	# Service section
	[params.services]
		headline = "Our Services"

    [[params.services.list]]
      icon = "fa-drupal"
      title = "Drupal"
      description = "High performance web applications built with the industrial-strength Drupal open source content management system."

    [[params.services.list]]
			icon = "fa-wordpress"
			title = "WordPress"
			description = "Stylishly themed portfolios and media rich blogs backed by the community-driven WordPress CMS."

		[[params.services.list]]
      icon = "fa-code"
      title = "Custom Code"
      description = "Hand-coded HTML5 websites and static site generation for highly-cacheable deployments."

    [[params.services.list]]
      icon = "fa-lock"
      title = "Security"
      description = "HTTPS encryption, DDoS protection, and intelligent firewall capabilities to keep sites and visitors secure."


  # Portfolio modals
	[params.portfolio.modal]
    client = "Client"
    date = "Date"
    category = "Category"
    buttonText = "Close"

  # Aside section
	[params.aside]
		headline = "See our work on GitHub"

		[params.aside.button]
			text = "Review Code"
			link = "//github.com/sjaconsulting"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "707-267-7752"
		email = "suzanne@sjaconsulting.com"
